### ISSUE TITLE
Fix README.md images

### ISSUE THREAD

**Issue by TechnicalWeeks** [TechnicalWeeks2023/playground-project#36]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/123472659/214936696-916b82bd-eaec-4dcd-995d-cf1f86e97f18.png">

**Comment by Ormared** [comment]
Fixed by this merge [https://github.com/TechnicalWeeks2023/playground-project/pull/35](https://github.com/TechnicalWeeks2023/playground-project/pull/35)
